FROM python:3.11-slim

# Install system dependencies for OpenCV and image handling for ultralytics
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY models_trained/modelv8m.pt models_trained/modelv8m.pt
COPY server.py .

# Environment variables
ENV PORT=8000
EXPOSE ${PORT}

CMD ["python", "server.py"]

